# Generated by Django 5.2.15 on 2026-09-04 10:48
# AI 用量记账：新增 AIUsageLog 统一流水表（NL2SQL/优化/审核/诊断四链路共用）

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0003_mongoslowquerydetail_mongoslowquerysummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('nl2sql', '自然语言生成SQL'), ('sql_optimize', 'SQL优化建议'), ('sql_review', 'SQL工单AI审核'), ('slowquery_diagnosis', 'AI慢查诊断')], max_length=32, verbose_name='AI能力')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='AI模型')),
                ('db_type', models.CharField(blank=True, default='', max_length=32, verbose_name='数据库类型')),
                ('instance_name', models.CharField(blank=True, default='', max_length=128, verbose_name='实例名')),
                ('db_name', models.CharField(blank=True, default='', max_length=128, verbose_name='数据库名')),
                ('user_name', models.CharField(blank=True, default='', max_length=128, verbose_name='触发用户')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='prompt token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='completion token数')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='是否命中缓存')),
                ('status', models.CharField(default='success', max_length=16, verbose_name='调用状态')),
                ('error', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI用量记账',
                'verbose_name_plural': 'AI用量记账',
                'db_table': 'ai_usage_log',
                'managed': True,
            },
        ),
    ]
