# Generated by Django 5.2.15 on 2026-09-04 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0004_aiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOptimizeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(blank=True, default='', max_length=128, verbose_name='数据库名')),
                ('db_type', models.CharField(blank=True, default='', max_length=32, verbose_name='数据库类型')),
                ('sql_hash', models.CharField(db_index=True, max_length=128, verbose_name='脱敏SQL指纹')),
                ('sql_text', models.TextField(blank=True, default='', verbose_name='脱敏后SQL')),
                ('table_names', models.JSONField(blank=True, default=list, verbose_name='解析出的表/集合名')),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='任务状态')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='AI模型')),
                ('report_markdown', models.TextField(blank=True, default='', verbose_name='优化报告')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Agent取证轨迹')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='prompt token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='completion token数')),
                ('error', models.CharField(blank=True, default='', max_length=500, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.instance', verbose_name='实例')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
            ],
            options={
                'verbose_name': 'AI优化任务',
                'verbose_name_plural': 'AI优化任务',
                'db_table': 'ai_optimize_task',
                'managed': True,
                'indexes': [models.Index(fields=['instance', 'db_name', 'sql_hash'], name='idx_aiopt_inst_db_hash')],
            },
        ),
    ]
