# Generated by Django 5.2.15 on 2026-09-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0005_aioptimizetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidiagnosisreport',
            name='report_markdown',
        ),
    ]
