# Generated by Django 5.2.15 on 2026-09-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0006_remove_report_markdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedisSlowQuery',
        ),
        migrations.DeleteModel(
            name='RedisSlowQueryHistory',
        ),
        migrations.DeleteModel(
            name='SlowQuery',
        ),
        migrations.DeleteModel(
            name='SlowQueryHistory',
        ),
    ]
